### ISSUE TITLE
Implement mock app

### ISSUE THREAD

**Issue by autotaker** [autotaker/smopeck#1]
# TODOs
- [x] Support UpperId and SQString for field
- [ ] Prelude spec file
- [ ] Convert http request to json object
- [ ] Convert HttpResponse object to http response
